services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka-1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_1_PORT}:${KAFKA_1_PORT}"
    networks:
      - app-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:${KAFKA_1_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:${KAFKA_1_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  kafka-2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-2
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_2_PORT}:${KAFKA_2_PORT}"
    networks:
      - app-network
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29192,PLAINTEXT_HOST://localhost:${KAFKA_2_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29192,PLAINTEXT_HOST://0.0.0.0:${KAFKA_2_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  kafka-3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-3
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_3_PORT}:${KAFKA_3_PORT}"
    networks:
      - app-network
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:29392,PLAINTEXT_HOST://localhost:${KAFKA_3_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29392,PLAINTEXT_HOST://0.0.0.0:${KAFKA_3_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  logger-service:
    build: ./Logger_service
    container_name: logger_service
    ports:
      - "${LOGGER_SERVICE_PORT}:${LOGGER_SERVICE_PORT}"
    environment:
      SERVER_PORT: "${LOGGER_SERVICE_PORT}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29192,kafka-3:29392
    networks:
      - app-network

  order-service:
    build: ./Order_service
    container_name: order_service
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      SERVER_PORT: "${ORDER_SERVICE_PORT}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29192,kafka-3:29392
    networks:
      - app-network

  order-service-2:
    build: ./Order_service
    container_name: order_service_2
    ports:
      - "${ORDER_SERVICE_2_PORT}:${ORDER_SERVICE_2_PORT}"
    environment:
      SERVER_PORT: "${ORDER_SERVICE_2_PORT}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29192,kafka-3:29392
    networks:
      - app-network

  order-service-3:
    build: ./Order_service
    container_name: order_service_3
    ports:
      - "${ORDER_SERVICE_3_PORT}:${ORDER_SERVICE_3_PORT}"
    environment:
      SERVER_PORT: "${ORDER_SERVICE_3_PORT}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29192,kafka-3:29392
    networks:
      - app-network

  transactional-service:
    build: ./Transactional_service
    container_name: transactional_service
    ports:
      - "${TRANSACTIONAL_SERVICE_PORT}:${TRANSACTIONAL_SERVICE_PORT}"
    environment:
      SERVER_PORT: "${TRANSACTIONAL_SERVICE_PORT}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29192,kafka-3:29392
    networks:
      - app-network

  transactional-db:
    image: postgres
    container_name: transactional_db
    ports:
      - "${TRANSACTIONAL_DB_PORT}:5432"
    environment:
      POSTGRES_DB: transactional_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    networks:
      - app-network

  transactional-service-2:
    build: ./Transactional_service
    container_name: transactional_service_2
    ports:
      - "${TRANSACTIONAL_SERVICE_2_PORT}:${TRANSACTIONAL_SERVICE_2_PORT}"
    environment:
      SERVER_PORT: "${TRANSACTIONAL_SERVICE_2_PORT}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29192,kafka-3:29392
    networks:
      - app-network

  transactional-db-2:
    image: postgres
    container_name: transactional_db_2
    ports:
      - "${TRANSACTIONAL_DB_2_PORT}:5432"
    environment:
      POSTGRES_DB: transactional_db_2
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    networks:
      - app-network

  transactional-service-3:
    build: ./Transactional_service
    container_name: transactional_service_3
    ports:
      - "${TRANSACTIONAL_SERVICE_3_PORT}:${TRANSACTIONAL_SERVICE_3_PORT}"
    environment:
      SERVER_PORT: "${TRANSACTIONAL_SERVICE_3_PORT}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-1:29092,kafka-2:29192,kafka-3:29392
    networks:
      - app-network

  transactional-db-3:
    image: postgres
    container_name: transactional_db_3
    ports:
      - "${TRANSACTIONAL_DB_3_PORT}:5432"
    environment:
      POSTGRES_DB: transactional_db_3
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
