spring:
  application:
    name: Transactional_service

  datasource:
    password: 123
    username: user
    url: jdbc:postgresql://transactional-db:5432/transactional_db
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: kafka-1:29092,kafka-2:29192,kafka-3:29392
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: transactional_service_group
      auto-offset-reset: earliest
      properties:
        spring.json.type.mapping: >
          org.example.order_service.OrderCreatedEvent:org.example.transactional_service.OrderCreatedEvent,
          org.example.order_service_2.OrderCreatedEvent:org.example.transactional_service.OrderCreatedEvent
        spring.json.trusted.packages: >
          org.example.logger_service,
          org.example.order_service,
          org.example.order_service_2,
          org.example.transactional_service,
          org.example.transactional_service_2
        spring.json.use.type.headers: true
        isolation.level: read_committed
        reconnect.backoff.ms: 5000
        reconnect.backoff.max.ms: 30000
        spring.kafka.consumer.properties.metadata.max.age.ms: 30000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tr-
      properties:
        spring.json.add.type.headers: true
        acks: all
        retries: 3
        enable.idempotence: true
        reconnect.backoff.ms: 5000
        reconnect.backoff.max.ms: 30000
        spring.kafka.consumer.properties.metadata.max.age.ms: 30000

server:
  port: ${SERVER_PORT:8080}